/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tristanchanson;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {

    public static final int WIDTH = 600;
    public static final int HEIGHT = 400;

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) {

        stage.setTitle("The Roller");

        Group root = new Group();
        Scene scene = new Scene(root, WIDTH, HEIGHT);

        Player player = new Player();
        root.getChildren().add(player);

        stage.setScene(scene);
        stage.show();

    }

}
